#!/bin/bash
# CAPACITY campaign driver: the buffer-capacity closure of `dsc/`, 18 units in 3 sub-campaigns.
#   port wave(s) -> promote session branch -> review pass -> promote -> deeptools gate
# Every stage's own log is under logs/; this script's own trace is logs/driver.trace.
#
# ⛔ EVERY GUARD BELOW IS A SCAR FROM THE BRIDGE-1, BRIDGE-2 AND DDC CAMPAIGNS. Do not simplify one
# away, and do not edit this file WHILE IT IS RUNNING — bash reads a script by byte offset, so an
# in-place edit reorders the rest of the run. Change it with `mv` onto a fresh copy.
# ⛔ NEVER COMMIT TO A BRANCH THIS DRIVER IS WRITING. That stranded 90 units on one campaign and 67
# on another.
ROOT=/Users/nickm/git/scratchy/.claude/worktrees/bridge1-pr
BRANCH=$(git -C $ROOT rev-parse --abbrev-ref HEAD)
CAMP=$ROOT/crustify/campaigns/capacity
LOGDIR=$CAMP/logs
TRACE=$LOGDIR/driver.trace
mkdir -p $LOGDIR
say() { echo "[$(date +%H:%M:%S)] $*" >> $TRACE; }

# ⭐ (0) ONE SHARED CARGO TARGET. Parallel agents each get their own worktree; without this each
# grows its own 6 GB target/ and the host wedges. It also means A GATE CAN GO GREEN ON SOMEONE
# ELSE'S BUILD — read the log, never just the exit code.
export CARGO_TARGET_DIR=$ROOT/target

# ⛔⛔ (1) SINGLE-INSTANCE LOCK. THREE SEPARATE INCIDENTS ON BRIDGE 2 CAME FROM TWO DRIVERS AT ONCE:
# duplicate drivers share every log path under $LOGDIR, each overwrites the other's stage log, and
# `promote` reads the session branch name OUT of that log. The older driver promoted a branch the
# younger one owned, HEAD moved sideways, and nine batches of finished work were stranded.
# ⛔⛔ NEVER `rm -f` THIS FILE TO CLEAR A "STALE" LOCK. The `kill -0` below already handles a
# genuinely stale lock. If a LIVE driver holds it, kill the driver and let its EXIT trap release it —
# and kill its `crustify` CHILD too, because killing the bash script alone reparents the child to
# init, which keeps spawning agents:
#     pkill -f 'crustify .*worktrees/bridge1-pr'
# ⚠ This path is deliberately NOT crustify/campaigns/.driver.lock — that file is TRACKED IN GIT and
# this worktree's checkout of it holds a pid owned by another worktree's driver.
LOCK=$CAMP/.driver.lock
if [ -e "$LOCK" ] && kill -0 "$(cat $LOCK 2>/dev/null)" 2>/dev/null; then
  echo "driver already running as pid $(cat $LOCK) — refusing to start a second" >&2
  say "REFUSED: driver already running as pid $(cat $LOCK)"
  exit 9
fi
echo $$ > "$LOCK"
trap 'rm -f "$LOCK"' EXIT INT TERM
say "LOCK acquired by pid $$ on $BRANCH"

# ⛔⛔ (2) THE .done MARKERS LIVE OUTSIDE THE CAMPAIGN DIR. crustify's `link_shared` symlinks the
# campaign directory into each agent worktree, which turned every .done-<tag> into a SYMLINK POINTING
# AT ITSELF: `[ -f ]` then failed, 7 batches died in 7 seconds.
STATE=$ROOT/.campaign-done
mkdir -p $STATE

# ⭐ (3) ANCHOR CENSUS — A PROGRESS SIGNAL, NEVER THE GATE. "1,076 units ported" once meant 238
# stubs. OUTSTANDING WORK IS JUDGED FROM UNITS.tsv AND FROM `todo!` COUNTS, never from anchors.
count() {
  filled=$(grep -rhoE '/// Replaces: e0(0[2-9]|1[0-9])_[A-Za-z0-9_]+' $ROOT/crates/compiler/deeptools/src | sort -u | wc -l | tr -d ' ')
  todos=$(grep -rc 'todo!' $ROOT/crates/compiler/deeptools/src/schedule/l3/capacity.rs 2>/dev/null | tr -d ' ')
  say "ANCHORS: filled=$filled of 18   todo! in capacity.rs=${todos:-n/a}"
}

# ⭐ (4) REMAINDER SCHEDULES, AND THE REMAINDER OVERRULES THE MARKER. Rebuild each
# port-remainder.json from the anchors actually filled on the branch: the schedules are static and
# crustify has no idea which units are done, so without this a restart re-ports what already landed.
remainders() {
  grep -rhoE '/// Replaces: e0(0[2-9]|1[0-9])_[A-Za-z0-9_]+' $ROOT/crates/compiler/deeptools/src \
    | sed 's|/// Replaces: ||' | sort -u > /tmp/filled-capacity.txt
  python3 $CAMP/regen-remainders.py >> $TRACE 2>&1
}

# ⭐ (5) PROMOTE BY FF-THEN-REBASE, never ff-or-die. A sideways HEAD — another promote, a hand
# commit — must not strand a stage's finished work on a session branch. On bridge 2 that stranded 48
# finished functions until they were rebased by hand.
promote() {
  br=$(grep -ohE 'crustify/session/[a-z]+-[0-9]{4}-[0-9]{2}-[0-9]{2}_[0-9]{2}-[0-9]{2}-[0-9]{2}_[0-9a-f]{4}' "$1" | tail -1)
  if [ -z "$br" ]; then say "PROMOTE: no session branch found in $1"; return 0; fi
  if git -C $ROOT merge --ff-only "$br" >> $TRACE 2>&1; then
    say "PROMOTE ok (ff): $br -> $(git -C $ROOT rev-parse --short HEAD)"
    remainders; return 0
  fi
  say "PROMOTE: not a fast-forward, rebasing $br onto $(git -C $ROOT rev-parse --short HEAD)"
  if git -C $ROOT rebase HEAD "$br" >> $TRACE 2>&1; then
    git -C $ROOT checkout - >> $TRACE 2>&1
    if git -C $ROOT merge --ff-only "$br" >> $TRACE 2>&1; then
      say "PROMOTE ok (rebased): $br -> $(git -C $ROOT rev-parse --short HEAD)"
      remainders; return 0
    fi
  fi
  git -C $ROOT rebase --abort >> $TRACE 2>&1
  git -C $ROOT checkout $BRANCH >> $TRACE 2>&1
  say "PROMOTE FAILED (rebase conflicted): $br — work is SAFE on that branch — STOPPING"
  exit 3
}

# ⭐ (6) DISK. Each agent worktree grows against the shared target/. Abort rather than wedge the host.
disk() {
  free=$(df -g $ROOT | awk 'NR==2{print $4}')
  say "DISK: ${free}G free"
  if [ "$free" -lt 12 ]; then say "DISK BELOW 12G — STOPPING"; exit 4; fi
}

# ⭐ (6) Prune promoted agent worktrees between stages, or the accumulated target/ dirs fill the disk.
prune() {
  git -C $ROOT worktree list --porcelain | grep -oE "$ROOT/crustify/.worktrees/[^ ]+" | while read -r w; do
    git -C $ROOT worktree remove --force "$w" >> $TRACE 2>&1
  done
  git -C $ROOT worktree prune >> $TRACE 2>&1
  say "PRUNED agent worktrees; $(df -g $ROOT | awk 'NR==2{print $4}')G free"
}

stage() { # $1 schedule json (relative to $CAMP)  $2 objective  $3 tag
  # ⭐ (7) SKIP A FINISHED STAGE — BUT THE REMAINDER OVERRULES THE MARKER. A .done marker beside a
  # NON-empty remainder means the marker is stale (a promote landed after it), so it is deleted and
  # the stage re-runs. Trusting the marker alone once had 9 agents re-reviewing 142 done functions.
  n=$(python3 -c "import json,sys;print(json.load(open(sys.argv[1]))['summary']['unit_count'])" "$CAMP/$1" 2>/dev/null || echo 1)
  if [ -f "$STATE/.done-$3" ]; then
    if [ "$n" = "0" ]; then
      say "STAGE $3 SKIPPED (.done-$3 present, remainder empty)"; return 0
    fi
    say "STAGE $3: .done-$3 present but remainder has $n units — MARKER IS STALE, re-running"
    rm -f "$STATE/.done-$3"
  fi
  if [ "$n" = "0" ]; then say "STAGE $3 SKIPPED (0 units left in $1)"; touch "$STATE/.done-$3"; return 0; fi
  disk
  # ⭐ (8) SMALL BATCHES, AND RETRY ONLY TRANSIENT API FAILURES — WITH AUTH CHECKED FIRST. crustify
  # promotes nothing until an agent completes, so at 50-unit batches an API drop at hour 4½ discarded
  # three agents' work. ⛔ AUTH FAILS FAST **BEFORE** THE TRANSIENT CHECK: retrying a 401 three times
  # at 120s burns 6 minutes and produces nothing, and the auth string can co-occur with a transient
  # one in the same log.
  for attempt in 1 2 3; do
    say "STAGE $3 start ($2, $1, $n units) attempt $attempt"
    crustify --parallel-max 3 $ROOT . translate "$CAMP/$1" --objective "$2" > $LOGDIR/driver-$3.log 2>&1
    rc=$?
    say "STAGE $3 attempt $attempt exit=$rc"
    [ $rc -eq 0 ] && break
    if grep -q "401 Authentication Error\|Invalid proxy server token\|Failed to authenticate\|Invalid API key" \
         $LOGDIR/driver-$3.log; then
      say "STAGE $3 AUTH FAILURE — not retrying, fix credentials and restart"; exit 7
    fi
    if ! grep -q "ENOTFOUND\|Can't reach the API server\|exited 1 for TranslateAgent" $LOGDIR/driver-$3.log; then
      say "STAGE $3 failed for a reason that is NOT the API — not retrying"; break
    fi
    say "STAGE $3 retrying in 120s (transient API failure)"; sleep 120
  done
  say "STAGE $3 exit=$rc"
  grep -E '^\[crustify\] [0-9]+ failure' $LOGDIR/driver-$3.log >> $TRACE 2>/dev/null
  promote $LOGDIR/driver-$3.log
  count
  prune
  touch "$STATE/.done-$3"
}

# ⛔ THE GATE IS deeptools ONLY. Never the workspace and never the acceptance build from here: 6 GB
# of target/ per agent worktree against <50 GB free.
gate() { # $1 tag
  ( cd $ROOT && cargo check -p deeptools > $LOGDIR/check-$1.log 2>&1 )
  say "CHECK $1 exit=$? :: $(grep -cE '^error' $LOGDIR/check-$1.log) errors"
  ( cd $ROOT && cargo test -p deeptools > $LOGDIR/test-$1.log 2>&1 )
  say "TEST $1 exit=$? :: $(grep -E '^test result' $LOGDIR/test-$1.log | tr '\n' ' ')"
  grep -E 'not yet implemented|panicked at|^error' $LOGDIR/check-$1.log $LOGDIR/test-$1.log | tail -5 >> $TRACE
}

say "=== CAPACITY CAMPAIGN START on $BRANCH at $(git -C $ROOT rev-parse --short HEAD) ==="
count
remainders

stage sc1-level0-leaves/port-remainder.json        port   sc1-port
stage sc1-level0-leaves/review.json                review sc1-review
gate sc1
stage sc2-levels1-2-dim-values/port-remainder.json port   sc2-port
stage sc2-levels1-2-dim-values/review.json         review sc2-review
gate sc2
stage sc3-levels3-6-capacity/port-remainder.json   port   sc3-port
stage sc3-levels3-6-capacity/review.json           review sc3-review
gate sc3
say "CAMPAIGN DRIVER DONE — 18 units is THIS CAMPAIGN'S SCOPE, not the stage and not the bridge"
