// SPDX-License-Identifier: Apache-2.0
//! THE MODEL-GEOMETRY DOOR — the only part of the KTIR → SuperDSC lowering that stays on this side,
//! and the reason it stays is that it cannot cross.
//!
//! ⭐ THE LOWERING ITSELF IS [`ktir_superdsc::emit::lower_ktir_to_superdsc`]. What is left here is
//! the name-keyed dispatch ([`lower`]) plus the two arms that turn a model's head geometry into
//! CONST GENERICS: [`scratchy_subtile::model_geometry`]'s `with_config_attn_geometry` /
//! `with_config_head_dim`, whose match arms are GENERATED by that crate's `build.rs` from every
//! checked-in `crates/models/arch/*/configs/*.json`.
//!
//! ⛔ THAT ARM SET IS THE CONSUMER'S MODEL INVENTORY, SO A LEAF CRATE MUST NOT OWN IT. It cannot be
//! received as data either — the whole point is that the values become `const` parameters, i.e. a
//! MONOMORPHISATION site. So the crate exposes
//! [`attn_at`](ktir_superdsc::emit::lower_ktir_to_superdsc::attn_at)`::<NQH, NKVH, HD>` and
//! [`rope_at`](ktir_superdsc::emit::lower_ktir_to_superdsc::rope_at)`::<HD>` as public generic entry
//! points and THE CALLER CROSSES THE DOOR. A third-party KTIR producer instantiates them from its
//! own configs; every build-time refusal here (a geometry with no arm is a loud bake error citing
//! `geometry_sources()`) is unchanged.
//!
//! ⭐⭐ AND THAT IS ALSO WHY THE MODEL'S AND THE BUNDLE'S OWN FACTS LIVE HERE. [`BundleAttnParams`] is
//! `ibm/main`'s `lower_one_node` parameter set for the attention path — the head geometry and the
//! attention multiplier off `SubOp::AttnDecode`, the swept rung and the row kind off the walk — and it
//! is an ARGUMENT of [`lower`], not a record on the program. `AttnFacts` was that record, and it let
//! the emulator (which executes the ops) and the card (which read the record) compute different
//! attention; the leaf crate now reads the six operand identities and the resident capacity out of the
//! program itself (`attn_operands`) and takes these four from whoever crossed the door.
//!
//! ⛔ THE TWO NEWTYPES BELOW ARE THE ORPHAN RULE, NOT A DESIGN. `OnAttnGeometry`/`OnHeadDim` are
//! `scratchy-subtile`'s traits and `AttnAt`/`RopeAt` are `ktir-superdsc`'s structs — neither is
//! local, so the impls need a type of THIS crate's own to hang on. They carry no logic: each wraps
//! the crate's argument pack and hands it straight to the generic entry point.

use ktir_superdsc::emit::EmittedOp;
use ktir_superdsc::emit::lower_ktir_to_superdsc as lk;
use ktir_superdsc::emit::lower_ktir_to_superdsc::{
    Error, Region, attn_at, elementwise, err, lmlast, matmul, regions, rmsnorm, rope_at,
    route_renorm, route_softmax, scalarmul, silumul, split_out,
};
use ktir_superdsc::ktir_node::{KtirNode, Program};
use ktir_superdsc::placement::BundleLayout;

/// ⭐⭐⭐ THE FOUR THINGS THE PROGRAM CANNOT STATE — `ibm/main`'s `lower_one_node` PARAMETERS, at the
/// site that now needs them.
///
/// main lowered each node during the tape walk, so it read these straight off what it had in hand:
/// the head geometry and the attention multiplier from `node.op`'s `SubOp::AttnDecode` payload (the
/// numbers the `#[forward]` macro parsed out of the model config), and `active_cap` /
/// `rows_are_requests` from its own walk parameters, threaded down from the ladder driver. This split
/// lowers per BUNDLE instead, one pass later, so the same four facts are stated for the bundle at the
/// same place they were read — and they are read ONCE, off the graph's own `AttnDecode` nodes, by
/// [`crate::lower_subtile_tape_to_ktir::attn_bundle_params`].
///
/// ⛔ THIS IS NOT A RECORD ON THE PROGRAM, AND THE DIFFERENCE IS THE WHOLE POINT. `AttnFacts` hung
/// eleven fields off [`KtirNode`], so information flowed `SubtileIR → AttnFacts → SuperDSC` past the
/// IR: a third-party producer could not fill it, and the emulator (which runs the ops) and the card
/// (which read the record) were not obliged to agree. Seven of those eleven are now read out of the
/// program by `attn_operands`; these four are ARGUMENTS of the call, one value per bundle, supplied by
/// the caller on THIS side of the geometry door — which is where model and bundle facts legitimately
/// live (see the module header). A Triton producer's caller states its own, from its own configs.
///
/// `None` for a bundle with no attention node: an attention program arriving without these is a build
/// error naming them, never a descriptor built on a default.
#[derive(Clone, Copy, Debug)]
pub struct BundleAttnParams {
    /// main's `lower_one_node(.., rows_are_requests, ..)`.
    ///
    /// ⛔ THE GEOMETRY IS NO LONGER HERE, AND THE REASON IS THE HYBRID MODEL. This used to carry the
    /// bundle's ONE `SubOp::AttnDecode { geom }` — a fact under the assumption that one `#[forward]`
    /// expansion has one attention geometry. Gemma-4 falsifies that assumption: its sliding layers run
    /// (nqh=16, nkvh=8, hd=256) and every sixth layer runs a GLOBAL class (nqh=16, nkvh=1, hd=512), so
    /// one graph carries TWO and no per-bundle value can describe both. The program's own views state
    /// the geometry of the attention they compute (`q`'s view is `[mq, nqh·hd]`, a kv stream's is
    /// `[·, nkvh·hd]`, and its first access tile on `q` is `hd` wide), so the door MINTS the geometry
    /// there — the same reading rope already does for its head dim, and the same direction the scale,
    /// `mq` and the swept extent all took: facts the program states are read from the program, and a
    /// fact only the caller knows stays a caller's argument. The row KIND is the one that stays: no
    /// program states it, for the reason its own comment gives.
    pub rows_are_requests: bool,
}

// ══════════════════════════════════════════════════════════════════════════════════════════════
//  THE DISPATCH — by the node kind the producer wrote into the program's name.
// ══════════════════════════════════════════════════════════════════════════════════════════════

/// One KTIR program → the SuperDSC descriptors main's body for that node kind emits.
///
/// `quantized` is main's own per-BUNDLE fp8 activation-quantize dedup set, threaded exactly as its
/// tape walk threaded it: q/k/v read one rms output and gate/up another, so each distinct activation
/// is quantized once and the later matmuls emit only `matmulfp8` + dequant.
///
/// `attn_params` is [`BundleAttnParams`] — main's own remaining parameters, for the two bodies whose
/// device laws need a fact no program states.
pub fn lower(
    k: &KtirNode,
    sym_id_base: &mut i64,
    layout: Option<&BundleLayout>,
    quantized: &mut std::collections::HashSet<String>,
    attn_params: Option<BundleAttnParams>,
) -> Result<Vec<EmittedOp>, Error> {
    // The name is still the program's identity for the emulator (which keys functions by it) and for
    // the descriptor suffixes, so it is READ — but nothing is parsed out of it.
    let name = k.func.name;
    let r = regions(k)?;
    // ⭐⭐⭐ ON THE TYPE, NOT ON THE NAME. This was `match name.split('_').next()`, so a program's kind
    // was a substring the producer wrote and this side parsed back out — a typo was a runtime refusal
    // and a new kind fell through a `_` arm. `KtirNode::program` states it, so there is NO catch-all
    // here and a producer that gains a kind is an E0004 at this match.
    match k.program {
        // `&[]` IS THE DENSE PATH, AND IT IS ARGUMENT 4. The broadcast flag slice is per-operand and
        // is stated by the whole-function walk from the region it read; a per-`Program` op has no
        // region to state one, and an empty slice is the byte-identical no-broadcast emission this
        // door always had. Measured: granite's baked descriptors are unchanged with this argument in
        // place, 2b and 8b at fp16 and fp8, `diff -r` 0 lines.
        //
        // ⛔ THE POSITION MATTERS AND THE COMPILER ONLY HALF-NAMES IT. `&[]` infers its element type
        // from whichever parameter it lands on, so writing it in slot 3 type-checks AS THE REGION LIST
        // and pushes the error onto the NEXT argument — `expected &[Option<BcastAxis>], found
        // &Vec<Region>` at `&r` — which reads as a problem with the regions rather than with where the
        // empty slice went. Measured that way: `cargo check -p scratchy-target-spyre` rc 101, against
        // rc 0 on main.
        Program::Elementwise(ew) => elementwise(name, ew, &r, &[], sym_id_base, layout),
        Program::SiluMul => silumul(name, &r, sym_id_base, layout),
        Program::RmsNorm => rmsnorm(name, k, &r, sym_id_base, layout),
        Program::RmsNormUnit => lk::rmsnorm_unit(name, k, &r, sym_id_base, layout),
        // The fused per-head norm sandwich — the door derives its geometry off the
        // program's own views (one head's window is the output's first access tile).
        Program::WindowedRmsNorm { .. } => lk::windowed_rmsnorm(name, k, &r, sym_id_base, layout),
        Program::TanhSoftCap => lk::tanhsoftcap(name, k, &r, sym_id_base, layout),
        // The router's row softmax/renorm — no geometry door to cross, no registry
        // const to resolve: the whole chain is data-driven and the body is the
        // rmsnorm's structure with the softmax's primitives in it.
        Program::RouteSoftmax => route_softmax(name, &r, sym_id_base, layout),
        Program::RouteRenorm => route_renorm(name, &r, sym_id_base, layout),
        // The expert MLP's gated activation — silumul's body with the act's own
        // device primitive (`silu`/`gelufwd`), over the pair rows the sort laid out.
        Program::ExpertGatedAct(act) => lk::gated_act(name, act, &r, sym_id_base, layout),
        Program::ScalarWeightMul => lk::scalarweightmul(name, &r, sym_id_base, layout),
        Program::Reshape => lk::reshape(name, &r, sym_id_base, layout),
        Program::ScalarMul => scalarmul(name, k, &r, sym_id_base, layout),
        Program::Matmul => matmul(name, &r, sym_id_base, layout, quantized),
        Program::LmLast => lmlast(name, k, &r, sym_id_base, layout),
        Program::Rope => rope(name, &r, sym_id_base, layout, attn_params),
        Program::Attn => attn(name, k, &r, sym_id_base, layout, attn_params),
        // ⭐ NO DOOR TO CROSS. A transpose's descriptor is parameterised by the two extents its own
        // program states and by nothing about the model, so the arm is the body — unlike `rope`/`attn`
        // above, whose head geometry has to become const generics on this side.
        Program::Transpose => lk::transpose(name, &r, sym_id_base, layout),
        // ── THE MoE ROUTING + EXPERT OPS, refused BY NAME — the `topk.ddl`
        // sort/mask vocabulary and the gather-bound weight binding are a
        // separate card-track worklist item, and a nearest-primitive
        // substitution would compute a different function. The EMULATOR runs
        // these programs' ops directly (`ktir_groups` ignores the Program
        // field off-card), so this refusal only fires under `-Fspyre-hw`.
        // Each row's expert indices sorted by ascending score, AS THE RANK
        // VECTOR — the compare/reduce form the emu states, one `j` at a time
        // with every token riding the mb axis (see the door's own doc for the
        // 7E+1 chain and the pad-mask sanitize that makes it correct).
        Program::RouteArgsort => lk::route_argsort(name, &r, sym_id_base, layout),
        Program::RouteTopK => Err(Error {
            message: format!(
                "{name}: RouteTopK (the last k sorted indices of each row) has no SuperDSC \
                 lowering yet: on card it is a k-wide slice of `topk.ddl`'s `topkindex` output"
            ),
        }),
        Program::RouteGatherScores => Err(Error {
            message: format!(
                "{name}: RouteGatherScores (the scores at the chosen indices) has no SuperDSC \
                 lowering yet: a row-wise gather by the top-k index tensor — the \
                 `indirectAccessIndexLabeledDs` + linked-index vocabulary of the paged KV gather, \
                 pointed at the score rows"
            ),
        }),
        Program::RouteExpertScale => Err(Error {
            message: format!(
                "{name}: RouteExpertScale (each score times its expert's learned scale) has no \
                 SuperDSC lowering yet: the RouteGatherScores gather reading \
                 `router.per_expert_scale` instead of the scores, then a pointwise mul"
            ),
        }),
        // The (token, slot) pair rows — `k` identity legs at stick-aligned column
        // offsets, the gathered regime's own statement that the permutation is a
        // no-op (metal's gathered bake emits nothing and reads token rows k times).
        Program::ExpertSort => lk::expert_sort(name, &r, sym_id_base, layout),
        // The pair rows back in token order — ONE identity over the whole
        // `[m, k·w]` tile, the materialized no-op of the same regime.
        Program::ExpertUnsort => lk::expert_unsort(name, &r, sym_id_base, layout),
        // The pair rows weighted by their routing scores and summed back into
        // the token stream — the per-slot fma chain, the add legs
        // accumulating into one scratch (in place, the softmax's own
        // destination-reuse law) and the final add writing the output.
        Program::ExpertCombine => lk::expert_combine(name, &r, sym_id_base, layout),
        Program::ExpertMatmul => Err(Error {
            message: format!(
                "{name}: ExpertMatmul (one projection of each pair's expert, over the stacked \
                 `[E·out, in]` weight bank) has no SuperDSC lowering yet: the contraction itself \
                 is the dense W8A8 body's, but the weight ROW each pair reads is selected by its \
                 expert index — an indexed operand the dense matmul's fixed region does not state"
            ),
        }),
    }
}

/// The orphan-rule carrier for [`lk::AttnAt`] — see the module header.
struct AttnAt<'a>(lk::AttnAt<'a>);

impl scratchy_subtile::model_geometry::OnAttnGeometry for AttnAt<'_> {
    type Out = Result<Vec<EmittedOp>, Error>;
    fn on_geometry<const NQH: u32, const NKVH: u32, const HD: u32>(
        self,
        geom: scratchy_subtile::sdsc_abstract::AttnGeometry<NQH, NKVH, HD>,
    ) -> Self::Out {
        attn_at::<NQH, NKVH, HD>(self.0, geom)
    }
}

/// ⭐ THE DOOR. main's `lower_attn_node` read its cache identity off `node.inputs` and `ir.tensors`,
/// its geometry and multiplier off the node's `SubOp`, and `active_cap`/`rows_are_requests` off its
/// call site. The cache identity and multiplier the PROGRAM states, so `attn_at` reads them there
/// (`attn_operands`); the row kind is [`BundleAttnParams`], main's own walk parameter, stated for
/// this bundle by the caller. `mq` is `q`'s own view's row count, which is what main's `TileOp` `mb`
/// dim was.
///
/// ⭐⭐ THE GEOMETRY IS MINTED HERE, OFF THE PROGRAM'S OWN VIEWS. It used to ride the bundle as one
/// `SubOp::AttnDecode { geom }` per expansion — sound only while one model had one attention class.
/// Gemma-4's layers alternate a SLIDING class (nqh=16, nkvh=8, hd=256) with a GLOBAL one
/// (nqh=16, nkvh=1, hd=512), so one graph carries two and no per-bundle value describes both. The
/// program states its own: `q`'s view is `[mq, nqh·hd]`, a kv stream's is `[·, nkvh·hd]`, and the
/// first access tile over `q` is `hd` wide — the same three readings `attn_operands` already makes
/// under a caller-stated geometry, so minting from them is not a new derivation but the existing one
/// with its input source moved. The GQA divisibility proof is spent at the same `mint` it always
/// was; a program whose views do not divide is a build error naming them.
fn attn(
    name: &str,
    k: &KtirNode,
    r: &[Region],
    sym_id_base: &mut i64,
    layout: Option<&BundleLayout>,
    attn_params: Option<BundleAttnParams>,
) -> Result<Vec<EmittedOp>, Error> {
    let p = attn_params.ok_or_else(|| Error {
        message: format!(
            "{name}: an attention program reached the lowering with no `BundleAttnParams`. Its row \
             kind is this bundle's (main's own walk parameter — whether its rows are separate \
             requests or one prompt's positions) and no KTIR states it, so the caller must state it \
             at the door."
        ),
    })?;
    // ── THE PROGRAM'S OWN GEOMETRY ── `q` is parameter 0 (checked against the store order in
    // `attn_operands`); a kv stream is the first K view after `q`/`out`; the head dim is the first
    // access tile's width over `q` — the tile whose corner is `arith.constant` at decode and
    // `pid·hd` at prefill, so the TILE's own Shape is the one reading that holds at both.
    let q = r.first().ok_or_else(|| Error {
        message: format!(
            "{name}: an attention program states {} parameter(s); its construction mints at least \
             six (q, out, and each segment's K then V)",
            r.len()
        ),
    })?;
    let kv_cols = {
        // The runtime length mask is a SYNTHETIC parameter (`[1, cap]`) that `KtirFunc::attn` mints
        // between `out` and the segments — `attn_operands` filters it by `k.mask`, and so does this
        // reading, or the mask's capacity would be read as a kv stream's width.
        let mask_tid = k.mask.map(|b| b.get());
        r.iter().skip(2).find_map(|x| {
            (x.tid != q.tid && Some(x.tid) != mask_tid && !x.is_out).then_some(x.v_cols)
        })
    };
    let (Some(q_cols), Some(kv_cols), Some((_, hd))) = (
        Some(q.v_cols),
        kv_cols,
        lk::param_first_tile(&k.func, &k.func.arguments[0].0),
    ) else {
        return Err(Error {
            message: format!(
                "{name}: the program does not state a complete geometry — `q`'s view is \
                 `[{}, ·]`, a kv stream is {} wide, and `q`'s first access tile is {} — one of the \
                 three is absent, so the head counts this door needs cannot be read off it",
                q.v_rows,
                kv_cols
                    .map(|c| c.to_string())
                    .unwrap_or_else(|| "missing".into()),
                lk::param_first_tile(&k.func, &k.func.arguments[0].0)
                    .map(|(_, c)| c.to_string())
                    .unwrap_or_else(|| "absent".into()),
            ),
        });
    };
    if hd == 0 || q_cols % hd != 0 || kv_cols % hd != 0 {
        return Err(Error {
            message: format!(
                "{name}: the program's own views do not divide into a geometry — `q` is {q_cols} \
                 wide, a kv stream {kv_cols}, the head-dim window {hd}; a head must tile both \
                 widths exactly or no GQA grouping exists"
            ),
        });
    }
    let geom = ktir_superdsc::head_counts::ModelAttnGeometry::mint(
        ktir_superdsc::head_counts::QueryHeads::new(q_cols / hd),
        ktir_superdsc::head_counts::KvHeads::new(kv_cols / hd),
        ktir_superdsc::head_counts::HeadDim::new(hd),
    )
    .ok_or_else(|| Error {
        message: format!(
            "{name}: the geometry read off the program's views (nqh={}, nkvh={}, head_dim={hd}) has \
             no GQA grouping — the kv-head count does not divide the query-head count, so \
             `AttnGeometry` cannot be named at it",
            q_cols / hd,
            kv_cols / hd,
        ),
    })?;
    // ⭐⭐ THE ONE PLACE THE MODEL'S HEAD GEOMETRY STOPS BEING VALUES for the attention path — the SAME
    // door `lower_one_node` crossed, now crossed with the geometry the program itself states.
    scratchy_subtile::model_geometry::with_config_attn_geometry(
        geom,
        AttnAt(lk::AttnAt {
            name,
            k,
            r,
            rows_are_requests: p.rows_are_requests,
            sym_id_base,
            layout,
        }),
    )
    .ok_or_else(|| Error {
        message: format!(
            "{name}: AttnDecode geometry ({geom}) has no const-generic instantiation. The head counts and \
             the head dim parameterise the device layout (GQA grouping, slabs, head strides), so \
             they must be consts, not values. The instantiations are read from the model configs in \
             scope ({}); this geometry belongs to none of them.",
            scratchy_subtile::model_geometry::geometry_sources(),
        ),
    })?
}

/// The orphan-rule carrier for [`lk::RopeAt`] — see the module header.
struct RopeAt<'a>(lk::RopeAt<'a>);

impl scratchy_subtile::model_geometry::OnHeadDim for RopeAt<'_> {
    type Out = Result<Vec<EmittedOp>, Error>;
    fn on_head_dim<const HD: u32>(self) -> Self::Out {
        rope_at::<HD>(self.0)
    }
}

/// ⭐ THE DOOR. main's `lower_rope_node` read `mq`/`total` off a `TileOp` built from the node and its
/// operand names off `ds_name`. `total` is the node's declared output width and `mq` its row count —
/// both carried on [`KtirNode::out_shape`], because the program states only their product with
/// `heads` (see that field). The head dim is the `x` view's own column extent, and it becomes the
/// const generic through the SAME door main crossed.
fn rope(
    name: &str,
    r: &[Region],
    sym_id_base: &mut i64,
    layout: Option<&BundleLayout>,
    attn_params: Option<BundleAttnParams>,
) -> Result<Vec<EmittedOp>, Error> {
    let (ins, out) = split_out(name, r, layout, 3)?;
    // `KtirFunc::rope` views `x` as `[rows·heads, hd]`, so the view's COLUMN extent is the head dim.
    let hd = ins[0].v_cols;
    // ⭐⭐⭐ ROWS AND WIDTH, BOTH READ OFF THE PROGRAM — AND THE READING IS THE TILE, NOT A VIEW.
    // `KtirFunc::rope` views `x` as `[rows·heads, hd]` and takes `self.tile(x_view, ri·heads, 0,
    // heads, half)` once per position, so the ACCESS TILE's row extent IS `heads` — the fact the two
    // view extents multiply together and neither states alone. `regions()` already records it as
    // `Region::r_len`. With `heads` known the view's own row count divides into the positions, and the
    // node's real width is `heads · hd`.
    //
    // ⛔ NOT THE COS VIEW. It looked like the answer — cos is one row per position — but `rope` binds
    // it through `load_1d(cos_t, rows·tbl_cols, ri·tbl_cols, half)`, i.e. ONE-DIMENSIONAL, so its view
    // is `(1, rows·tbl_cols)` and its row extent is 1 for every model. Reading it as the position
    // count made granite-3.1-8b's `[2, 4096]` rope output into `[1, 8192]`, which the arrangement
    // authority caught as a same-tensor layout conflict on t729. The half-width is `c_len` here, so
    // `hd == 2 · c_len` is checked below rather than assumed.
    let heads = ins[0].r_len;
    if heads == 0 || hd == 0 {
        return err(format!(
            "{name}: the `x` view states `[{}, {hd}]` and its access tile {heads} row(s) — a rope \
             needs a nonzero head dim and at least one head",
            ins[0].v_rows,
        ));
    }
    if ins[0].v_rows % heads != 0 {
        return err(format!(
            "{name}: the `x` view states {} row(s) over an access tile of {heads} head(s), which does \
             not divide — `KtirFunc::rope` views `x` as `rows·heads` by `hd`, so the head count must \
             tile its rows exactly",
            ins[0].v_rows,
        ));
    }
    if ins[0].c_len * 2 != hd {
        return err(format!(
            "{name}: the `x` access tile takes {} column(s) of a {hd}-wide view — a rope rotates \
             half-width slices, so the window must be exactly `hd / 2`",
            ins[0].c_len,
        ));
    }
    let mq = ins[0].v_rows / heads;
    let total = heads * hd;
    // ⛔ THE ROW KIND, AS A PARAMETER — main's `LowerRope::rows_are_requests`, which main also took as
    // a parameter and for the reason its own comment gives. It decides whether the head-major collapse
    // may span the query rows, which is a DEVICE law: `KtirFunc::rope` never receives the fact and
    // emits the same ops either way, so no program can state it. A rope in a bundle with no attention
    // node has no requests to have rows of, which is main's own `false` at that call site.
    let rows_are_requests = attn_params.is_some_and(|p| p.rows_are_requests);
    // ⭐⭐ THE ONE PLACE THE HEAD DIM STOPS BEING A VALUE, the same door `lower_one_node` crossed for
    // the SubtileIR path: the arms are every head dim the workspace's model configs declare, and a
    // head dim with no arm is a loud bake error answered by a `config.json`.
    if hd == 0 {
        return err(format!("{name}: the `x` view states a zero head dim"));
    }
    // ⭐ THE ROPE-P CLASS TID — which `[hd,hd]` P table this rope's `matmul(x, P)` names. The class
    // set is the bake's OWN registry (`BundleLayout::rope_class_hds`, the same registry mechanism
    // `scalarmul_scales` established), so the emitter, the placement pass and the worker's load-time
    // bind all resolve class↔tid through ONE list. A rope arriving with no registry, or a head dim
    // the registry does not hold, is a desync — refuse it rather than guessing class 0.
    let p_tid = layout
        .and_then(|l| l.rope_class_hds.iter().position(|&h| h == hd))
        .map(ktir_superdsc::reserved_tids::rope_p_class_tid)
        .ok_or_else(|| Error {
            message: format!(
                "{name}: rope head_dim {hd} absent from BundleLayout.rope_class_hds {:?} (registry \
                 desync — the placement pass and this lowering disagree about the tape's rope \
                 classes, so which P table this rope reads is not a fact either of them states)",
                layout.map(|l| l.rope_class_hds.clone()).unwrap_or_default(),
            ),
        })?;
    scratchy_subtile::model_geometry::with_config_head_dim(
        scratchy_subtile::model_geometry::HeadDim::new(hd),
        RopeAt(lk::RopeAt {
            name,
            x: ins[0].name(),
            cos: ins[1].name(),
            sin: ins[2].name(),
            out: out.name(),
            t: out.tid,
            mq,
            total,
            p_tid,
            sym_id_base,
            layout,
            rows_are_requests,
        }),
    )
    .ok_or_else(|| Error {
        message: format!(
            "{name}: head_dim {hd} has no const-generic instantiation. The head dim parameterises \
             the device layout (slabs = head_dim/lanes, and the head-major collapse is valid only at \
             head_dim == lanes), so it must be a const, not a value. The instantiations are read \
             from the model configs in scope ({}); this head dim belongs to none of them.",
            scratchy_subtile::model_geometry::geometry_sources(),
        ),
    })?
}
